# Generated by Django 5.2.5 on 2025-08-06 19:53

import django.db.models.deletion
import django_ckeditor_5.fields
import main.fields
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория новости',
                'verbose_name_plural': 'Категории новостей',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Раздел сайта')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Раздел сайта',
                'verbose_name_plural': 'Разделы сайта',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True)),
                ('unsubscribe_token', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Подписчика',
                'verbose_name_plural': 'Подписчики',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Текст')),
                ('photo', main.fields.WEBPField(blank=True, null=True, upload_to=main.models.image_folder, verbose_name='фото 633x550px')),
                ('content2', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст2')),
                ('photo2', main.fields.WEBPField(blank=True, null=True, upload_to=main.models.image_folder, verbose_name='фото2')),
                ('photo3', main.fields.WEBPField(blank=True, null=True, upload_to=main.models.image_folder, verbose_name='Фото№3')),
                ('content3', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст3')),
                ('photo4', main.fields.WEBPField(blank=True, null=True, upload_to=main.models.image_folder, verbose_name='Фото№4')),
                ('photo5', main.fields.WEBPField(blank=True, null=True, upload_to=main.models.image_folder, verbose_name='Фото№5')),
                ('content4', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст4')),
                ('time_create', models.DateTimeField(verbose_name='Дата и время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.categorynews', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['time_create', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Текст')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Цена')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото2')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото3')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото4')),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото5')),
                ('photo6', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото6')),
                ('time_create', models.DateTimeField(verbose_name='Дата и время создания')),
                ('time_update', models.DateTimeField(verbose_name='Дата и время обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('number_of_employees', models.IntegerField(default=0, verbose_name='Количество сотрудников')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'unique_together': {('title', 'slug')},
            },
        ),
    ]
