# Generated by Django 5.2.5 on 2026-01-05 16:44

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import main.fields
import main.mixins
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactgroup_contact_contactrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Удобство')),
                ('icon', models.CharField(blank=True, max_length=80, verbose_name='Иконка (fa/bi)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Удобство',
                'verbose_name_plural': 'Удобства',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание')),
                ('default_capacity', models.IntegerField(default=2, verbose_name='Вместимость по умолчанию')),
                ('default_beds', models.CharField(blank=True, max_length=120, verbose_name='Кровати по умолчанию')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Категория номера',
                'verbose_name_plural': 'Категории номеров',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название (витрина)')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='Номер (например 101)')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Площадь (м²)')),
                ('capacity', models.IntegerField(default=2, verbose_name='Вместимость')),
                ('beds', models.CharField(blank=True, max_length=120, verbose_name='Кровати')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Цена за ночь')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('check_in_from', models.TimeField(blank=True, null=True, verbose_name='Заезд с')),
                ('check_out_to', models.TimeField(blank=True, null=True, verbose_name='Выезд до')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('inactive', 'Скрыт'), ('maintenance', 'На обслуживании')], default='active', max_length=20, verbose_name='Статус')),
                ('photo', main.fields.WEBPField(blank=True, null=True, upload_to=main.models.room_image_folder, verbose_name='Фото (обложка)')),
                ('photo2', main.fields.WEBPField(blank=True, null=True, upload_to=main.models.room_image_folder, verbose_name='Фото2')),
                ('photo3', main.fields.WEBPField(blank=True, null=True, upload_to=main.models.room_image_folder, verbose_name='Фото3')),
                ('photo4', main.fields.WEBPField(blank=True, null=True, upload_to=main.models.room_image_folder, verbose_name='Фото4')),
                ('photo5', main.fields.WEBPField(blank=True, null=True, upload_to=main.models.room_image_folder, verbose_name='Фото5')),
                ('time_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('amenities', models.ManyToManyField(blank=True, related_name='rooms', to='main.roomamenity', verbose_name='Удобства')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='main.roomcategory', verbose_name='Категория номера')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'ordering': ['number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=120, verbose_name='Имя гостя')),
                ('guest_phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('guest_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('date_from', models.DateField(verbose_name='Дата заезда')),
                ('date_to', models.DateField(verbose_name='Дата выезда')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Итого')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('cancelled', 'Отменена'), ('completed', 'Завершена')], default='new', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='main.room', verbose_name='Номер')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['room', 'date_from', 'date_to'], name='main_roombo_room_id_142800_idx'), models.Index(fields=['status'], name='main_roombo_status_dc5a79_idx')],
            },
            bases=(models.Model, main.mixins.OccupancyMixin),
        ),
    ]
