# Generated by Django 5.2.5 on 2026-01-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_roomamenity_roomcategory_alter_service_time_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='adults',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Взрослые'),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='children',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Дети'),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='guests',
            field=models.PositiveSmallIntegerField(default=2, help_text='Автоматически рассчитывается: взрослые + дети', verbose_name='Всего гостей'),
        ),
    ]
